### ISSUE TITLE
Online updates broken in 3.1.2

### ISSUE THREAD

**Issue by RadioAndrea** [rt-bishop/Look4Sat#103]
Online updates are broken on Look4Sat version 3.1.2 on Android version 13.

This impacts the google play, fdroid, and direct apk versions.

Transceivers are read in from web source successfully, but satellites are not. File imports are functioning as expected.

Error message is as shown in the screenshot.

Downgrading to 3.1.0 resolves the issue.

I unfortunately cannot find any logs

![Imagepipe_1](https://user-images.githubusercontent.com/7978519/204959116-d6822e91-0180-4328-bc8e-16741bf7c071.jpg)

**Comment by rt-bishop** [comment]
I know it's a late reply, but I haven't seen any issues in the data update on any Android version within this whole month (I use 13 myself and test on various). The data import code is shared between the Online and Manual import, so this means that the issue is with the data collection from online providers. Probably some of the remote urls were not accessible/slow/down/blocked. Also there were no Fetching/Import related code changes, so v3.1.0 gathers the data it in the same way v3.1.2 does. The only difference is v3.1.2 has an additional source - R4UAB is a Russian data source and can potentially be blocked in some places.
