### ISSUE TITLE
Descriptive names of satellites (feature request)

### ISSUE THREAD

**Issue by jcp-sd** [rt-bishop/Look4Sat#31]
I noticed that the descriptive names of the satellites changed with one of the recent updates.

After digging into the code a little, it seems to be related to the addition of the Amsat TLE file to the update from the web feature.

For example;

Celestrak has the string: `SAUDISAT 1C (SO-50)` for ID 27607

Amsat has the more terse string: `SO-50` for ID 27607

In the recent release, the later string is what survives, making it a bit more tricky to find a given satellite if you are not familiar with _all_ the different descriptive names that are floating around.

It should not be hard to do a "smart merge" of the two files. In this case, picking the string with more characters in it seems to be straight forward way to make the right choice.

Hopefully I am not coming across as being overly critical, but it does destroy the otherwise great user experience to some degree. For others who are bothered by this, a quick work around is to just remove the Amsat TLE from the update from web menu (as it's names seem to almost always be more terse).

Otherwise, great program. It's like having gpredict in your pocket or brief case. The upcoming pass display is very well thought out and communicates the most important information quickly and accurately.

73, John

**Comment by rt-bishop** [comment]
Thank you very much John for your kind words and for this feature request! However, the naming change was made because I received a number of complains, emails and requests from other users that prefer to use Amsat given names and prefered to overwrite the Celestrak names by default. The same behaviour is in Gpredict program that I often use as a reference. So I think no further changes should be made to the naming scheme. The workaround that you suggested also fixes the issue entirely.
