### ISSUE TITLE
Feature request: Earth's shadow

### ISSUE THREAD

**Issue by ropufu** [rt-bishop/Look4Sat#62]
It would be really awesome if you could incorporate satellite's visibility into the program. Although it might not be all that useful for a lot of the satellites, for ISS, for example, that would be a game-changer. Knowing when it goes in or out of the Earth's shadow would make the app so much more interesting for a small (but I hope non-negligible) portion of users. Thank you thank you :^)

**Comment by ctand** [comment]
This is a bigger issue than just visibility. Showing the eclipse of a satellite will help to prevent misuse by amateur radio hobbyists of satellites that should not be keyed up during eclipse due to battery status. If not a filter then at least denoting passes in eclipse and maybe a note not to operate during eclipse would be great. Both AO-91 and AO-92 come to mind. Gpredict has this feature. Thanks!
