### ISSUE TITLE
Predictions/Position's for Russian Weather Sats are very incorrect

### ISSUE THREAD

**Issue by Gregor077** [rt-bishop/Look4Sat#80]
About two Days ago I updated the TLE's over the Update Button in the App. Since then the position from all the Russian Sats are incorrect, Elektro L2 hasn't moved yet and The LEO Sats passes are wrong..
Probably some Faulty Tle's.

**Comment by rt-bishop** [comment]
@Gregor077 Hey! Thanks for reporting this. It happens because of a recently found bug in CSV data parser class. It's quite simple to temporarily fix it until I release a new version. Go to data update, scroll to the end of "celestrak" source url and swap csv for tle after the = sign. I've fixed the bug in my developer branch already, so if more users report problems I'll release a quick fix.
