### ISSUE TITLE
Don't view all satellites on the map

### ISSUE THREAD

**Issue by qwerty287** [rt-bishop/Look4Sat#93]
This is kind of a a bug:
1. Select all satellites
2. Open the map

It will load a while and is unusable then. My suggestion would be to only display the next ~10 satellites on the map to improve performance of it. Thanks!

**Comment by rt-bishop** [comment]
Hello! Thanks for the suggestion. Although I don't understand what's the issue here. I can't alter the user's decision in a hidden way. If the user wants all 6k satellites - there you go. Also, one does not simply need the map to track satellites, it's there to be a fancy decoration. So there is no usecase for tracking 6k satellites and observing them on the map.

**Comment by rt-bishop** [comment]
No, definitely don't want to do that. Because the use case doesn't seem valid to me.

**Comment by ckuethe** [comment]
As a practical matter, how would one decide on subset of x satellites to display? Let's say I select all the starlinks... what would be a good strategy to select which ones to show? What if there are some I always want to know about wherever they are (ISS), potentially in relation to some other constellation (eg. Iridium?) - how would I pin the ISS to never be downsampled? What if the constellation I'm interested in is just a couple satellites larger than the arbitrary limit?

I'm with @rt-bishop on this... just display what the user selected, and let them decide on the set of satellites that are interesting enough relative to the refresh rate.
